version: "3.8"

services:
  nginx:
    build: ./infra/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build: ./infra/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: ./infra/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
